title: Advanced Information Systems Laboratory
url: "https://www.iaaa.es"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Next generation spatial data infrastructures and location intelligence.

# Other data for the jekyll-seo-tag gem
logo: /images/logo-share.svg
twitter:
    username: iaaa_lab

# Author details for the jekyll-seo-tag gem
author:
  name: IAAA
  email: iaaa@unizar.es
  twitter: iaaa_lab

# Social details for the jekyll-seo-tag gem
social:    
  links:
    - https://github.com/iaaa-lab
    - https://twitter.com/iaaa_lab

collections:
  staff:
    output: true
  projects:
    output: true
    permalink: /:name # Con esto un tin2018.md dentro de _projects tendrá ruta www.iaaa.es/tin2018
    # Sin la línea anterior, la ruta sería www.iaaa.es/projects/tin2018

paginate: 5
paginate_path: "/blog/:num/"
permalink: pretty

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "contents"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
# Por defecto saldrá esta imagen al insertar un post etc. en un enlace en red social. Poner un image
# específico en el front matter de los posts etc. si se quiere otra cosa
  - scope:            
      path: ""
    values:
      image: /images/earth_night.jpg

#social_icons:
# - Facebook
# - Google Plus
# - Instagram
#  - LinkedIn
# - Pinterest
# - Tumblr
#  - Twitter
#  - YouTube
#  - GitHub
# - RSS
